### ISSUE TITLE
App in use

### ISSUE THREAD

**Issue by kababoom** [kababoom/temp-repo#1]
@w2016561536 hope you get this message.

The app is a banking app so rather keep this a bit private although I'm not hacking the app in any way, just trying to automate some functions in it.

Here's the play store link:
https://play.google.com/store/apps/details?id=com.db.coo.secureauthenticator&hl=en_US&gl=US

And a link to a QR Code:
https://user-images.githubusercontent.com/16404944/144584136-22245d56-fa57-4b8b-a9af-213e8b6483b9.mp4

Original image:
![download](https://user-images.githubusercontent.com/16404944/144584637-d5d3958a-a8d0-41f7-85f4-304e9a5ef624.jpeg)

When starting the app choose a pin, then activate via QR Code.

The qr is expired so you should get a message with 'An error occured' if you get that then the process is working. 

Cheers,
-M

**Comment by w2016561536** [comment]
Got it

从 Windows 版邮件发送

发件人: kababoom
发送时间: 2021年12月3日 18:08
收件人: kababoom/temp-repo
抄送: w2016561536; Mention
主题: [kababoom/temp-repo] App in use (Issue #1)

@w2016561536 hope you get this message.
The app is a banking app so rather keep this a bit private although I'm not hacking the app in any way, just trying to automate some functions in it.
Here's the play store link:
https://play.google.com/store/apps/details?id=com.db.coo.secureauthenticator&hl=en_US&gl=US
And a link to a QR Code:
https://user-images.githubusercontent.com/16404944/144584136-22245d56-fa57-4b8b-a9af-213e8b6483b9.mp4
Original image:

When starting the app choose a pin, then activate via QR Code.
The qr is expired so you should get a message with 'An error occured' if you get that then the process is working.
Cheers,
-M

**Comment by w2016561536** [comment]
I have tested that it definitely workable
You need to adjust the video's resulution to 720*480
Please read the README before raise a question

**Comment by w2016561536** [comment]
https://user-images.githubusercontent.com/40821031/144715674-50feecbc-f46d-4e88-b8b2-0f715030f256.mp4

**Comment by kababoom** [comment]
@w2016561536 Tested about a thousand different vid resolutions but none worked hence I thought it did not trigger it correctly, apologies .....

Awesome work..😎

Do you have donation options?

**Comment by w2016561536** [comment]
No
But thanks for your support
